export const eventsAddress = "0xDCF6fbBbbF83848Bf68500432392C0988712Bf43";

export const eventsABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_eventStub", type: "address", internalType: "address" },
      { name: "_eventPoints", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allowlist",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "autoEndEvent",
    inputs: [{ name: "eventId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "bulkRemoveFromAllowlist",
    inputs: [
      { name: "eventId", type: "uint256", internalType: "uint256" },
      { name: "attendees", type: "address[]", internalType: "address[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "bulkSetAllowlist",
    inputs: [
      { name: "eventId", type: "uint256", internalType: "uint256" },
      { name: "attendees", type: "address[]", internalType: "address[]" },
      { name: "allowed", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "checkIn",
    inputs: [{ name: "eventId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "checkedIn",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createEvent",
    inputs: [
      { name: "eventId", type: "uint256", internalType: "uint256" },
      { name: "stubId", type: "uint256", internalType: "uint256" },
      { name: "points", type: "uint256", internalType: "uint256" },
      { name: "startTime", type: "uint256", internalType: "uint256" },
      { name: "endTime", type: "uint256", internalType: "uint256" },
      { name: "maxCapacity", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deleteEvent",
    inputs: [{ name: "eventId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "eventPoints",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract Points" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "eventStub",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract Stubs" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "events",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "stubId", type: "uint256", internalType: "uint256" },
      { name: "points", type: "uint256", internalType: "uint256" },
      { name: "startTime", type: "uint256", internalType: "uint256" },
      { name: "endTime", type: "uint256", internalType: "uint256" },
      { name: "maxCapacity", type: "uint256", internalType: "uint256" },
      { name: "totalCheckedIn", type: "uint256", internalType: "uint256" },
      { name: "exists", type: "bool", internalType: "bool" },
      { name: "paused", type: "bool", internalType: "bool" },
      { name: "allowlistRequired", type: "bool", internalType: "bool" },
      { name: "isAutoEnded", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEventCheckInCount",
    inputs: [{ name: "eventId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEventDetails",
    inputs: [{ name: "eventId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "stubId", type: "uint256", internalType: "uint256" },
      { name: "points", type: "uint256", internalType: "uint256" },
      { name: "startTime", type: "uint256", internalType: "uint256" },
      { name: "endTime", type: "uint256", internalType: "uint256" },
      { name: "maxCapacity", type: "uint256", internalType: "uint256" },
      { name: "totalCheckedIn", type: "uint256", internalType: "uint256" },
      { name: "exists", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEventStatus",
    inputs: [{ name: "eventId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "exists", type: "bool", internalType: "bool" },
      { name: "paused", type: "bool", internalType: "bool" },
      { name: "hasStarted", type: "bool", internalType: "bool" },
      { name: "hasEnded", type: "bool", internalType: "bool" },
      { name: "isAtCapacity", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isEventActive",
    inputs: [{ name: "eventId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isUserAllowlisted",
    inputs: [
      { name: "eventId", type: "uint256", internalType: "uint256" },
      { name: "user", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isUserCheckedIn",
    inputs: [
      { name: "eventId", type: "uint256", internalType: "uint256" },
      { name: "user", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pauseEvent",
    inputs: [{ name: "eventId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setAllowlist",
    inputs: [
      { name: "eventId", type: "uint256", internalType: "uint256" },
      { name: "attendees", type: "address[]", internalType: "address[]" },
      { name: "allowed", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unpause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unpauseEvent",
    inputs: [{ name: "eventId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateEventCapacity",
    inputs: [
      { name: "eventId", type: "uint256", internalType: "uint256" },
      { name: "newMaxCapacity", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateEventPoints",
    inputs: [
      { name: "eventId", type: "uint256", internalType: "uint256" },
      { name: "newPoints", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateEventPointsContract",
    inputs: [{ name: "newPoints", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateEventStub",
    inputs: [
      { name: "eventId", type: "uint256", internalType: "uint256" },
      { name: "newStubId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateEventStubContract",
    inputs: [{ name: "newStub", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateEventTimes",
    inputs: [
      { name: "eventId", type: "uint256", internalType: "uint256" },
      { name: "newStartTime", type: "uint256", internalType: "uint256" },
      { name: "newEndTime", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AllowlistUpdated",
    inputs: [
      {
        name: "eventId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "user", type: "address", indexed: true, internalType: "address" },
      { name: "allowed", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BulkAllowlistUpdated",
    inputs: [
      {
        name: "eventId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "count",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CheckInReversed",
    inputs: [
      {
        name: "eventId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "user", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CheckedIn",
    inputs: [
      {
        name: "eventId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "points",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "stubId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EventCapacityUpdated",
    inputs: [
      {
        name: "eventId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "oldCapacity",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newCapacity",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EventCreated",
    inputs: [
      {
        name: "eventId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "stubId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "points",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "startTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "endTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "maxCapacity",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EventDeleted",
    inputs: [
      {
        name: "eventId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EventEnded",
    inputs: [
      {
        name: "eventId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EventPaused",
    inputs: [
      {
        name: "eventId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EventPointsContractUpdated",
    inputs: [
      {
        name: "oldPoints",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newPoints",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EventPointsUpdated",
    inputs: [
      {
        name: "eventId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "newPoints",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EventStubContractUpdated",
    inputs: [
      {
        name: "oldStub",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newStub",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EventStubUpdated",
    inputs: [
      {
        name: "eventId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "newStubId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EventTimesUpdated",
    inputs: [
      {
        name: "eventId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "oldStartTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "oldEndTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newStartTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newEndTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EventUnpaused",
    inputs: [
      {
        name: "eventId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EventUpdated",
    inputs: [
      {
        name: "eventId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "startTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "endTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "maxCapacity",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Paused",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "EnforcedPause", inputs: [] },
  { type: "error", name: "ExpectedPause", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
];
