-- Player geo location: countries + geo_cities cache + player FKs.
-- Keeps legacy players.city / players.country text columns.
-- Does NOT modify the curated events/guides cities table.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS countries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  iso2 CHAR(2) NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT countries_iso2_unique UNIQUE (iso2)
);

CREATE INDEX IF NOT EXISTS idx_countries_name ON countries (name);

CREATE TABLE IF NOT EXISTS geo_cities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  country_id UUID NOT NULL REFERENCES countries(id) ON DELETE RESTRICT,
  mapbox_id TEXT NOT NULL,
  name TEXT NOT NULL,
  region TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT geo_cities_mapbox_id_unique UNIQUE (mapbox_id)
);

CREATE INDEX IF NOT EXISTS idx_geo_cities_country_name
  ON geo_cities (country_id, name);

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS country_id UUID REFERENCES countries(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS geo_city_id UUID REFERENCES geo_cities(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_players_country_id ON players (country_id);
CREATE INDEX IF NOT EXISTS idx_players_geo_city_id ON players (geo_city_id);

COMMENT ON TABLE countries IS 'ISO 3166-1 countries for player location targeting.';
COMMENT ON TABLE geo_cities IS 'Mapbox-backed city cache; rows created when players select a city.';
COMMENT ON COLUMN players.country_id IS 'FK to countries for marketing targeting; legacy country text kept.';
COMMENT ON COLUMN players.geo_city_id IS 'FK to geo_cities for marketing targeting; legacy city text kept.';

INSERT INTO countries (id, iso2, name) VALUES
  (gen_random_uuid(), 'AF', 'Afghanistan'),
  (gen_random_uuid(), 'AL', 'Albania'),
  (gen_random_uuid(), 'DZ', 'Algeria'),
  (gen_random_uuid(), 'AS', 'American Samoa'),
  (gen_random_uuid(), 'AD', 'Andorra'),
  (gen_random_uuid(), 'AO', 'Angola'),
  (gen_random_uuid(), 'AI', 'Anguilla'),
  (gen_random_uuid(), 'AQ', 'Antarctica'),
  (gen_random_uuid(), 'AG', 'Antigua and Barbuda'),
  (gen_random_uuid(), 'AR', 'Argentina'),
  (gen_random_uuid(), 'AM', 'Armenia'),
  (gen_random_uuid(), 'AW', 'Aruba'),
  (gen_random_uuid(), 'AU', 'Australia'),
  (gen_random_uuid(), 'AT', 'Austria'),
  (gen_random_uuid(), 'AZ', 'Azerbaijan'),
  (gen_random_uuid(), 'BS', 'Bahamas'),
  (gen_random_uuid(), 'BH', 'Bahrain'),
  (gen_random_uuid(), 'BD', 'Bangladesh'),
  (gen_random_uuid(), 'BB', 'Barbados'),
  (gen_random_uuid(), 'BY', 'Belarus'),
  (gen_random_uuid(), 'BE', 'Belgium'),
  (gen_random_uuid(), 'BZ', 'Belize'),
  (gen_random_uuid(), 'BJ', 'Benin'),
  (gen_random_uuid(), 'BM', 'Bermuda'),
  (gen_random_uuid(), 'BT', 'Bhutan'),
  (gen_random_uuid(), 'BO', 'Bolivia'),
  (gen_random_uuid(), 'BQ', 'Bonaire, Sint Eustatius and Saba'),
  (gen_random_uuid(), 'BA', 'Bosnia and Herzegovina'),
  (gen_random_uuid(), 'BW', 'Botswana'),
  (gen_random_uuid(), 'BV', 'Bouvet Island'),
  (gen_random_uuid(), 'BR', 'Brazil'),
  (gen_random_uuid(), 'IO', 'British Indian Ocean Territory'),
  (gen_random_uuid(), 'BN', 'Brunei Darussalam'),
  (gen_random_uuid(), 'BG', 'Bulgaria'),
  (gen_random_uuid(), 'BF', 'Burkina Faso'),
  (gen_random_uuid(), 'BI', 'Burundi'),
  (gen_random_uuid(), 'CV', 'Cabo Verde'),
  (gen_random_uuid(), 'KH', 'Cambodia'),
  (gen_random_uuid(), 'CM', 'Cameroon'),
  (gen_random_uuid(), 'CA', 'Canada'),
  (gen_random_uuid(), 'KY', 'Cayman Islands'),
  (gen_random_uuid(), 'CF', 'Central African Republic'),
  (gen_random_uuid(), 'TD', 'Chad'),
  (gen_random_uuid(), 'CL', 'Chile'),
  (gen_random_uuid(), 'CN', 'China'),
  (gen_random_uuid(), 'CX', 'Christmas Island'),
  (gen_random_uuid(), 'CC', 'Cocos (Keeling) Islands'),
  (gen_random_uuid(), 'CO', 'Colombia'),
  (gen_random_uuid(), 'KM', 'Comoros'),
  (gen_random_uuid(), 'CG', 'Congo'),
  (gen_random_uuid(), 'CD', 'Congo, Democratic Republic of the'),
  (gen_random_uuid(), 'CK', 'Cook Islands'),
  (gen_random_uuid(), 'CR', 'Costa Rica'),
  (gen_random_uuid(), 'CI', 'Côte d''Ivoire'),
  (gen_random_uuid(), 'HR', 'Croatia'),
  (gen_random_uuid(), 'CU', 'Cuba'),
  (gen_random_uuid(), 'CW', 'Curaçao'),
  (gen_random_uuid(), 'CY', 'Cyprus'),
  (gen_random_uuid(), 'CZ', 'Czechia'),
  (gen_random_uuid(), 'DK', 'Denmark'),
  (gen_random_uuid(), 'DJ', 'Djibouti'),
  (gen_random_uuid(), 'DM', 'Dominica'),
  (gen_random_uuid(), 'DO', 'Dominican Republic'),
  (gen_random_uuid(), 'EC', 'Ecuador'),
  (gen_random_uuid(), 'EG', 'Egypt'),
  (gen_random_uuid(), 'SV', 'El Salvador'),
  (gen_random_uuid(), 'GQ', 'Equatorial Guinea'),
  (gen_random_uuid(), 'ER', 'Eritrea'),
  (gen_random_uuid(), 'EE', 'Estonia'),
  (gen_random_uuid(), 'SZ', 'Eswatini'),
  (gen_random_uuid(), 'ET', 'Ethiopia'),
  (gen_random_uuid(), 'FK', 'Falkland Islands'),
  (gen_random_uuid(), 'FO', 'Faroe Islands'),
  (gen_random_uuid(), 'FJ', 'Fiji'),
  (gen_random_uuid(), 'FI', 'Finland'),
  (gen_random_uuid(), 'FR', 'France'),
  (gen_random_uuid(), 'GF', 'French Guiana'),
  (gen_random_uuid(), 'PF', 'French Polynesia'),
  (gen_random_uuid(), 'TF', 'French Southern Territories'),
  (gen_random_uuid(), 'GA', 'Gabon'),
  (gen_random_uuid(), 'GM', 'Gambia'),
  (gen_random_uuid(), 'GE', 'Georgia'),
  (gen_random_uuid(), 'DE', 'Germany'),
  (gen_random_uuid(), 'GH', 'Ghana'),
  (gen_random_uuid(), 'GI', 'Gibraltar'),
  (gen_random_uuid(), 'GR', 'Greece'),
  (gen_random_uuid(), 'GL', 'Greenland'),
  (gen_random_uuid(), 'GD', 'Grenada'),
  (gen_random_uuid(), 'GP', 'Guadeloupe'),
  (gen_random_uuid(), 'GU', 'Guam'),
  (gen_random_uuid(), 'GT', 'Guatemala'),
  (gen_random_uuid(), 'GG', 'Guernsey'),
  (gen_random_uuid(), 'GN', 'Guinea'),
  (gen_random_uuid(), 'GW', 'Guinea-Bissau'),
  (gen_random_uuid(), 'GY', 'Guyana'),
  (gen_random_uuid(), 'HT', 'Haiti'),
  (gen_random_uuid(), 'HM', 'Heard Island and McDonald Islands'),
  (gen_random_uuid(), 'VA', 'Holy See'),
  (gen_random_uuid(), 'HN', 'Honduras'),
  (gen_random_uuid(), 'HK', 'Hong Kong'),
  (gen_random_uuid(), 'HU', 'Hungary'),
  (gen_random_uuid(), 'IS', 'Iceland'),
  (gen_random_uuid(), 'IN', 'India'),
  (gen_random_uuid(), 'ID', 'Indonesia'),
  (gen_random_uuid(), 'IR', 'Iran'),
  (gen_random_uuid(), 'IQ', 'Iraq'),
  (gen_random_uuid(), 'IE', 'Ireland'),
  (gen_random_uuid(), 'IM', 'Isle of Man'),
  (gen_random_uuid(), 'IL', 'Israel'),
  (gen_random_uuid(), 'IT', 'Italy'),
  (gen_random_uuid(), 'JM', 'Jamaica'),
  (gen_random_uuid(), 'JP', 'Japan'),
  (gen_random_uuid(), 'JE', 'Jersey'),
  (gen_random_uuid(), 'JO', 'Jordan'),
  (gen_random_uuid(), 'KZ', 'Kazakhstan'),
  (gen_random_uuid(), 'KE', 'Kenya'),
  (gen_random_uuid(), 'KI', 'Kiribati'),
  (gen_random_uuid(), 'KP', 'Korea, Democratic People''s Republic of'),
  (gen_random_uuid(), 'KR', 'Korea, Republic of'),
  (gen_random_uuid(), 'KW', 'Kuwait'),
  (gen_random_uuid(), 'KG', 'Kyrgyzstan'),
  (gen_random_uuid(), 'LA', 'Lao People''s Democratic Republic'),
  (gen_random_uuid(), 'LV', 'Latvia'),
  (gen_random_uuid(), 'LB', 'Lebanon'),
  (gen_random_uuid(), 'LS', 'Lesotho'),
  (gen_random_uuid(), 'LR', 'Liberia'),
  (gen_random_uuid(), 'LY', 'Libya'),
  (gen_random_uuid(), 'LI', 'Liechtenstein'),
  (gen_random_uuid(), 'LT', 'Lithuania'),
  (gen_random_uuid(), 'LU', 'Luxembourg'),
  (gen_random_uuid(), 'MO', 'Macao'),
  (gen_random_uuid(), 'MG', 'Madagascar'),
  (gen_random_uuid(), 'MW', 'Malawi'),
  (gen_random_uuid(), 'MY', 'Malaysia'),
  (gen_random_uuid(), 'MV', 'Maldives'),
  (gen_random_uuid(), 'ML', 'Mali'),
  (gen_random_uuid(), 'MT', 'Malta'),
  (gen_random_uuid(), 'MH', 'Marshall Islands'),
  (gen_random_uuid(), 'MQ', 'Martinique'),
  (gen_random_uuid(), 'MR', 'Mauritania'),
  (gen_random_uuid(), 'MU', 'Mauritius'),
  (gen_random_uuid(), 'YT', 'Mayotte'),
  (gen_random_uuid(), 'MX', 'Mexico'),
  (gen_random_uuid(), 'FM', 'Micronesia'),
  (gen_random_uuid(), 'MD', 'Moldova'),
  (gen_random_uuid(), 'MC', 'Monaco'),
  (gen_random_uuid(), 'MN', 'Mongolia'),
  (gen_random_uuid(), 'ME', 'Montenegro'),
  (gen_random_uuid(), 'MS', 'Montserrat'),
  (gen_random_uuid(), 'MA', 'Morocco'),
  (gen_random_uuid(), 'MZ', 'Mozambique'),
  (gen_random_uuid(), 'MM', 'Myanmar'),
  (gen_random_uuid(), 'NA', 'Namibia'),
  (gen_random_uuid(), 'NR', 'Nauru'),
  (gen_random_uuid(), 'NP', 'Nepal'),
  (gen_random_uuid(), 'NL', 'Netherlands'),
  (gen_random_uuid(), 'NC', 'New Caledonia'),
  (gen_random_uuid(), 'NZ', 'New Zealand'),
  (gen_random_uuid(), 'NI', 'Nicaragua'),
  (gen_random_uuid(), 'NE', 'Niger'),
  (gen_random_uuid(), 'NG', 'Nigeria'),
  (gen_random_uuid(), 'NU', 'Niue'),
  (gen_random_uuid(), 'NF', 'Norfolk Island'),
  (gen_random_uuid(), 'MK', 'North Macedonia'),
  (gen_random_uuid(), 'MP', 'Northern Mariana Islands'),
  (gen_random_uuid(), 'NO', 'Norway'),
  (gen_random_uuid(), 'OM', 'Oman'),
  (gen_random_uuid(), 'PK', 'Pakistan'),
  (gen_random_uuid(), 'PW', 'Palau'),
  (gen_random_uuid(), 'PS', 'Palestine, State of'),
  (gen_random_uuid(), 'PA', 'Panama'),
  (gen_random_uuid(), 'PG', 'Papua New Guinea'),
  (gen_random_uuid(), 'PY', 'Paraguay'),
  (gen_random_uuid(), 'PE', 'Peru'),
  (gen_random_uuid(), 'PH', 'Philippines'),
  (gen_random_uuid(), 'PN', 'Pitcairn'),
  (gen_random_uuid(), 'PL', 'Poland'),
  (gen_random_uuid(), 'PT', 'Portugal'),
  (gen_random_uuid(), 'PR', 'Puerto Rico'),
  (gen_random_uuid(), 'QA', 'Qatar'),
  (gen_random_uuid(), 'RE', 'Réunion'),
  (gen_random_uuid(), 'RO', 'Romania'),
  (gen_random_uuid(), 'RU', 'Russian Federation'),
  (gen_random_uuid(), 'RW', 'Rwanda'),
  (gen_random_uuid(), 'BL', 'Saint Barthélemy'),
  (gen_random_uuid(), 'SH', 'Saint Helena, Ascension and Tristan da Cunha'),
  (gen_random_uuid(), 'KN', 'Saint Kitts and Nevis'),
  (gen_random_uuid(), 'LC', 'Saint Lucia'),
  (gen_random_uuid(), 'MF', 'Saint Martin'),
  (gen_random_uuid(), 'PM', 'Saint Pierre and Miquelon'),
  (gen_random_uuid(), 'VC', 'Saint Vincent and the Grenadines'),
  (gen_random_uuid(), 'WS', 'Samoa'),
  (gen_random_uuid(), 'SM', 'San Marino'),
  (gen_random_uuid(), 'ST', 'Sao Tome and Principe'),
  (gen_random_uuid(), 'SA', 'Saudi Arabia'),
  (gen_random_uuid(), 'SN', 'Senegal'),
  (gen_random_uuid(), 'RS', 'Serbia'),
  (gen_random_uuid(), 'SC', 'Seychelles'),
  (gen_random_uuid(), 'SL', 'Sierra Leone'),
  (gen_random_uuid(), 'SG', 'Singapore'),
  (gen_random_uuid(), 'SX', 'Sint Maarten'),
  (gen_random_uuid(), 'SK', 'Slovakia'),
  (gen_random_uuid(), 'SI', 'Slovenia'),
  (gen_random_uuid(), 'SB', 'Solomon Islands'),
  (gen_random_uuid(), 'SO', 'Somalia'),
  (gen_random_uuid(), 'ZA', 'South Africa'),
  (gen_random_uuid(), 'GS', 'South Georgia and the South Sandwich Islands'),
  (gen_random_uuid(), 'SS', 'South Sudan'),
  (gen_random_uuid(), 'ES', 'Spain'),
  (gen_random_uuid(), 'LK', 'Sri Lanka'),
  (gen_random_uuid(), 'SD', 'Sudan'),
  (gen_random_uuid(), 'SR', 'Suriname'),
  (gen_random_uuid(), 'SJ', 'Svalbard and Jan Mayen'),
  (gen_random_uuid(), 'SE', 'Sweden'),
  (gen_random_uuid(), 'CH', 'Switzerland'),
  (gen_random_uuid(), 'SY', 'Syrian Arab Republic'),
  (gen_random_uuid(), 'TW', 'Taiwan'),
  (gen_random_uuid(), 'TJ', 'Tajikistan'),
  (gen_random_uuid(), 'TZ', 'Tanzania'),
  (gen_random_uuid(), 'TH', 'Thailand'),
  (gen_random_uuid(), 'TL', 'Timor-Leste'),
  (gen_random_uuid(), 'TG', 'Togo'),
  (gen_random_uuid(), 'TK', 'Tokelau'),
  (gen_random_uuid(), 'TO', 'Tonga'),
  (gen_random_uuid(), 'TT', 'Trinidad and Tobago'),
  (gen_random_uuid(), 'TN', 'Tunisia'),
  (gen_random_uuid(), 'TR', 'Türkiye'),
  (gen_random_uuid(), 'TM', 'Turkmenistan'),
  (gen_random_uuid(), 'TC', 'Turks and Caicos Islands'),
  (gen_random_uuid(), 'TV', 'Tuvalu'),
  (gen_random_uuid(), 'UG', 'Uganda'),
  (gen_random_uuid(), 'UA', 'Ukraine'),
  (gen_random_uuid(), 'AE', 'United Arab Emirates'),
  (gen_random_uuid(), 'GB', 'United Kingdom'),
  (gen_random_uuid(), 'US', 'United States'),
  (gen_random_uuid(), 'UM', 'United States Minor Outlying Islands'),
  (gen_random_uuid(), 'UY', 'Uruguay'),
  (gen_random_uuid(), 'UZ', 'Uzbekistan'),
  (gen_random_uuid(), 'VU', 'Vanuatu'),
  (gen_random_uuid(), 'VE', 'Venezuela'),
  (gen_random_uuid(), 'VN', 'Viet Nam'),
  (gen_random_uuid(), 'VG', 'Virgin Islands (British)'),
  (gen_random_uuid(), 'VI', 'Virgin Islands (U.S.)'),
  (gen_random_uuid(), 'WF', 'Wallis and Futuna'),
  (gen_random_uuid(), 'EH', 'Western Sahara'),
  (gen_random_uuid(), 'YE', 'Yemen'),
  (gen_random_uuid(), 'ZM', 'Zambia'),
  (gen_random_uuid(), 'ZW', 'Zimbabwe')
ON CONFLICT (iso2) DO NOTHING;

