-- Retired. Favorites were merged into player_location_checkins.visit_status
-- (want_to_try, unless the player had already checked in).
-- Do not recreate player_location_favorites.
-- See database/player-location-visit-status.sql.
